namespace STW.ProcessingApi.Function.UnitTests.TestHelpers;

public static class TestConstants
{
    public const string True = "TRUE";
    public const string False = "False";
    public const string DestinationRegisteredNumber = "1234";
    public const string Invalid = "invalid";
    public const string ShipName = "SS STW";
    public const string ShipPort = "Felixstowe";
    public const string BcpCode = "GBFXT1PP";
    public const string NewZealand = "New Zealand";
    public const string GreatBritainIsoCode = "GB";
    public const string NewZealandIsoCode = "NZ";
    public const string AfghanistanIsoCode = "AF";
    public const string AlbaniaIsoCode = "AL";
    public const string AlgeriaIsoCode = "DZ";
    public const string AndorraIsoCode = "AD";
    public const string AngolaIsoCode = "AO";
    public const string ArgentinaIsoCode = "AR";
    public const string ArmeniaIsoCode = "AM";
    public const string AustraliaIsoCode = "AU";
    public const string AustriaIsoCode = "AT";
    public const string AzerbaijanIsoCode = "AZ";
    public const string BahamasIsoCode = "BS";
    public const string BahrainIsoCode = "BH";
    public const string BangladeshIsoCode = "BD";
    public const string UnitedKingdomIsoCode = "GB";
    public const string ScotlandRegionCode = "GB-SCO";
    public const string WalesRegionCode = "GB-WLS";
    public const string ScientificName = "Scientific Name";
    public const string SpeciesTypeName = "Species Type Name";
    public const string SpeciesClassName = "Species Class Name";
    public const string SpeciesFamilyName = "Species Family Name";
    public const string ClassCode = "Class Code";
    public const string StemsKey = "STM";
    public const string BulbsKey = "BLB";
    public const string CormsAndRhizomesKey = "CRZ";
    public const string PlantsAndTissueCultureKey = "PTC";
    public const string SeedsKey = "SDS";
    public const string KilogramsKey = "KGM";
    public const string PiecesKey = "PCS";
    public const string Variety = "Variety";
    public const string Class = "Class";
    public const string OperatorId = "ME26";
    public const string OperatorName = "Silver Fern Farms Limited - Pareora";
    public const string OperatorRoleCode = "Meat of domestic ungulates";
    public const string Slaughterhouses = "Slaughterhouses";
    public const string SlaughterhousesCode = "SH";
    public const string HttpClientBaseAddress = "https://example.com";
    public const string CommodityId = "12345678";
    public const string EppoCode = "MABSD";
}
